apiVersion: v1
kind: Service
metadata:
  name: allow-list-registry
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: allow-list-registry
  labels:
    app: allow-list-registry
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: allow-list-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allow-list-registry
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/csantanapr/allow-list-registry
  labels:
    app: allow-list-registry
    version: v1
    app.kubernetes.io/component: allow-list-registry
    app.kubernetes.io/instance: allow-list-registry
    app.kubernetes.io/name: allow-list-registry
    app.kubernetes.io/part-of: allow-list-registry
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "14"
spec:
  selector:
    matchLabels:
      app: allow-list-registry
      version: v1
  template:
    metadata:
      labels:
        app: allow-list-registry
        version: v1
    spec:
      volumes:
      - name: certs
        secret:
          secretName: allow-list-registry
      containers:
        - name: allow-list-registry
          image: allow-list-registry
          ports:
            - containerPort: 8443
              name: https
          env:
          - name: ALLOW_LISTED_REGISTRIES
            value: "docker.io,gcr.io"
          envFrom:
            - secretRef:
                name: allow-list-registry
          volumeMounts:
          - name: certs
            mountPath: "/certs"
            readOnly: true
          livenessProbe:
            tcpSocket:
              port: 8443
          readinessProbe:
            tcpSocket:
              port: 8443