apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: allow-list-registry
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- name: dev.cloudnativetoolkit.allow-list-registry
  namespaceSelector:
    matchExpressions:
    - key: cntk
      operator: In
      values:
      - experiment
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: default
      name: allow-list-registry
      path: "/"
  admissionReviewVersions: ["v1"]
  sideEffects: None